### PR TITLE
Annotate GraphQL ID Types with `@graphql:ID` Annotation in Service Generation

### PR DESCRIPTION
**Pull request by Ishad-M-I-M**
Fixes: [#6381](https://github.com/ballerina-platform/ballerina-library/issues/6381)

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by DimuthuMadushan** [comment]
@Ishad-M-I-M One of the test case (testGenerateSrcForSchemaWithGraphQLIDType) is failing in both ubuntu and windows build. Could you please check?

**Comment by Ishad-M-I-M** [comment]
> @Ishad-M-I-M One of the test case (testGenerateSrcForSchemaWithGraphQLIDType) is failing in both ubuntu and windows build. Could you please check?

Fixed it

**Review by DimuthuMadushan — APPROVED** [review]
LGTM!

**Review by ThisaruGuruge — APPROVED** [review]
LGTM

**Review by ThisaruGuruge — APPROVED** [review]
LGTM

**Pull request merged**
